//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProUpgradeEditor
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProUpgradeEditor.ProResources", typeof(ProResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap CDRom
        {
            get
            {
                object obj = ResourceManager.GetObject("CDRom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap cross
        {
            get
            {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap doc_music
        {
            get
            {
                object obj = ResourceManager.GetObject("doc_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap folder_classic_type_music
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_classic_type_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap folder_explore
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_explore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap folder_modernist_type_music
        {
            get
            {
                object obj = ResourceManager.GetObject("folder_modernist_type_music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap grayround
        {
            get
            {
                object obj = ResourceManager.GetObject("grayround", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap greenGrad1
        {
            get
            {
                object obj = ResourceManager.GetObject("greenGrad1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightBlueFade
        {
            get
            {
                object obj = ResourceManager.GetObject("lightBlueFade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightBlueFade2
        {
            get
            {
                object obj = ResourceManager.GetObject("lightBlueFade2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightGrayAlphaFade
        {
            get
            {
                object obj = ResourceManager.GetObject("lightGrayAlphaFade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightGraySmall
        {
            get
            {
                object obj = ResourceManager.GetObject("lightGraySmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightGraySmall2
        {
            get
            {
                object obj = ResourceManager.GetObject("lightGraySmall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightGraySmall21
        {
            get
            {
                object obj = ResourceManager.GetObject("lightGraySmall21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap lightGraySmall3
        {
            get
            {
                object obj = ResourceManager.GetObject("lightGraySmall3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music
        {
            get
            {
                object obj = ResourceManager.GetObject("music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music__1_
        {
            get
            {
                object obj = ResourceManager.GetObject("music__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music__exclamation
        {
            get
            {
                object obj = ResourceManager.GetObject("music__exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music__minus
        {
            get
            {
                object obj = ResourceManager.GetObject("music__minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music__pencil
        {
            get
            {
                object obj = ResourceManager.GetObject("music__pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music__plus
        {
            get
            {
                object obj = ResourceManager.GetObject("music__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music_beam
        {
            get
            {
                object obj = ResourceManager.GetObject("music_beam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music_beam_16
        {
            get
            {
                object obj = ResourceManager.GetObject("music_beam_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music_green
        {
            get
            {
                object obj = ResourceManager.GetObject("music_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap music_grey
        {
            get
            {
                object obj = ResourceManager.GetObject("music_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap OpenFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Partition
        {
            get
            {
                object obj = ResourceManager.GetObject("Partition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Task
        {
            get
            {
                object obj = ResourceManager.GetObject("Task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap tb3
        {
            get
            {
                object obj = ResourceManager.GetObject("tb3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static byte[] Thumbs
        {
            get
            {
                object obj = ResourceManager.GetObject("Thumbs", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static System.Drawing.Bitmap topbottom
        {
            get
            {
                object obj = ResourceManager.GetObject("topbottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap topbottom1
        {
            get
            {
                object obj = ResourceManager.GetObject("topbottom1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap topbottomblue
        {
            get
            {
                object obj = ResourceManager.GetObject("topbottomblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap topbottomwhite
        {
            get
            {
                object obj = ResourceManager.GetObject("topbottomwhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ui_text_field_clear
        {
            get
            {
                object obj = ResourceManager.GetObject("ui_text_field_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBBlueArrow
        {
            get
            {
                object obj = ResourceManager.GetObject("USBBlueArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBExcl
        {
            get
            {
                object obj = ResourceManager.GetObject("USBExcl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBFlash
        {
            get
            {
                object obj = ResourceManager.GetObject("USBFlash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBGreenPlus
        {
            get
            {
                object obj = ResourceManager.GetObject("USBGreenPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBLogo
        {
            get
            {
                object obj = ResourceManager.GetObject("USBLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBPencil
        {
            get
            {
                object obj = ResourceManager.GetObject("USBPencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap USBRedMinus
        {
            get
            {
                object obj = ResourceManager.GetObject("USBRedMinus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap x
        {
            get
            {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap XBJoy
        {
            get
            {
                object obj = ResourceManager.GetObject("XBJoy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap xgif
        {
            get
            {
                object obj = ResourceManager.GetObject("xgif", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap XPDrive
        {
            get
            {
                object obj = ResourceManager.GetObject("XPDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap XPFolder
        {
            get
            {
                object obj = ResourceManager.GetObject("XPFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap XPLens
        {
            get
            {
                object obj = ResourceManager.GetObject("XPLens", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap XPRecycle
        {
            get
            {
                object obj = ResourceManager.GetObject("XPRecycle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
